export { default as CreatePost } from './createPost'
export { default as Discover } from './discover'
export { default as Error } from './error'
export { default as Login } from './login'
export { default as Main } from './main'
export { default as CreateRest } from './createRest'
export { default as Profile } from './profile'
export { default as Verify } from './verify'
